parameters:
- name: environment_name
  type: string
- name: environment_file
  type: string

steps:
  - task: AzureCLI@2
    displayName: Register Azure ML environment (conda)
    continueOnError: false
    inputs: 
      azureSubscription: $(AZURE_RM_SVC_CONNECTION)
      scriptType: bash
      workingDirectory: $(System.DefaultWorkingDirectory)
      scriptLocation: inlineScript
      inlineScript: |
        az ml environment create --name ${{ parameters.environment_name }} --file ${{ parameters.environment_file }}
