parameters:
- name: cluster_name
  type: string
- name: size
  type: string
  default: STANDARD_D4S_V3
- name: min_instances
  type: number
  default: 0
- name: max_instances
  type: number
  default: 4
- name: cluster_tier
  type: string
  default: dedicated

steps:
  - task: AzureCLI@2
    displayName: Create Azure ML Compute Cluster
    inputs: 
      azureSubscription: $(AZURE_RM_SVC_CONNECTION)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        compute_name=$(az ml compute show -n ${{ parameters.cluster_name }} --query name -o tsv)
        if [[ -z "$compute_name" ]]
        then
          echo "Compute does not exists. Creating the cluster..."
          az ml compute create --name ${{ parameters.cluster_name }} \
                                  --type amlcompute \
                                  --size ${{ parameters.size }} \
                                  --min-instances ${{ parameters.min_instances }} \
                                  --max-instances ${{ parameters.max_instances }} \
                                  --tier ${{ parameters.cluster_tier }} 
        else
          echo "Compute exists. Skipping cluster creation."
          exit 0
        fi