jobs:
- job: WaitForCallback
  pool: server
  timeoutInMinutes: 0
  dependsOn: Submit_Job_Pipeline
  variables: 
    run_name_from_submit_job: $[ dependencies.Submit_Job_Pipeline.outputs['submit_aml_job_task.RUN_NAME'] ] 
  steps:
  - task: AMLJobWaitTask@0
    inputs:
      # a service connection with Azure ML scope (see the doc from the link above)
      azureSubscription: 'azuremlconnection'
      runName: $(run_name_from_submit_job)