jobs:
- job: WaitForCallback
  pool: server
  timeoutInMinutes: 0
  dependsOn: Submit_Job_Pipeline
  variables: 
    run_name_from_submit_job: $[ dependencies.Submit_Job_Pipeline.outputs['submit_aml_job_task.RUN_NAME'] ] 
  steps:
  - task: AzureMLJobWaitTask@0
    inputs:
      # https://github.com/Azure/azure-mlops-automation
      # a service connection with Azure ML scope (see the doc from the link above)
      serviceConnection: $(AZURE_RM_SVC_CONNECTION)
      resourceGroupName: $(RESOURCE_GROUP)
      azureMLWorkspaceName: $(WORKSPACE_NAME)
      azureMLWorkspaceLocation: $(CLUSTER_REGION)
      azureMLJobName: $(run_name_from_submit_job)